# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bce48d32821bc31ebde70d4ce7f32ce4892d6662cc987e4d1220810a58eedf14f9b200af33b40f96766a67809f6df5dab477d2ec4d64945d3b95e0a79cd1a03b

test:
  secret_key_base: 9554b42c24ef0fede2dc403cc416158a880208e074e4423b88746d9bf10725bc135517667c7a269912d2c67ba616d50989a4c678754b1b6d97fe84a0ecc46712

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
